### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by shazow** [sahava/spam-filter-tool#2]
Hi there, I'm actually building my own similar tool and stumbled on yours. Some suggestions:
- https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt is a great list for known referral spammers.
- The filters are regular expressions, so technically you want to escape the period character (e.g. `foo\.com`). In practice, this doesn't matter too much as there aren't hostnames without periods that we need to worry about matching accidentally.
- You can combine domains to make shorter expressions (e.g. `foo\.com|bar\.com|baz\.com` into `(foo|bar|baz)\.com`). In fact, you can take it even further (e.g. `(foo|ba[rz])\.com`).

**Comment by dailybits** [comment]
Hi,

I'm offline until wednesday evening on a sailboat without Wifi. ;-)

When you're bored, I suggest you start (re)reading all blogposts on www.dailybits.be


Greetings,


Herman
www.dailybits.be
herman@dailybits.be

**Comment by sahava** [comment]
Hey,

Thanks for the suggestions!

I'm using the Loan Goat resource which provides pre-edited RegEx filters, and I'm happy with that. You can, of course, simply modify the Array in the JS to suit your needs better, and improve the RegEx yourself.

As for the period character, as you say, hostnames always require a period, so we're actually saving characters by omitting the backward slash.

There's some work going on around an API that would pull from the Piwik list, so I will probably adapt the library to start using that instead at some point. Then I'll definitely work on the algorithm that chops up an arbitrary list of host names into usable GA filter regexes.

Simo
