### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shazow** [sahava/spam-filter-tool#3]
What license are you releasing this code under?

If you pick something that lets me reuse this in my own project, I'd be happy to contribute and improve it. :)

I suggest MIT.

**Comment by sahava** [comment]
I haven't given the licence any thought as I don't have any ambitions towards this project "product-wise". So feel free to grab the code and do what you want with it - others have already done so :)

Naturally, if you want to give a shout out and link to this GitHub repo it would be appreciated.

I'll take a look at the licences once I find some time :-) Thanks!

**Comment by shazow** [comment]
Unfortunately it works the other way around.

If you're not specifying a license, then by default your code is copyright protected and nobody else is allowed to legally use or change it without your explicit permission (aka specifying a license). You can legally pursue anyone who has taken your code and reappropriated it.

If you'd like for people to legally use your work and contribute to it, please pick a license. :)

If you don't care what people use it for (aka "do what you want with it, just don't hold me liable") then MIT or BSD are a great choice. If you want to place restrictions on making proprietary forks of the code, then GPL-like licenses are a good choice.

Some resources:
https://programmers.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it

> Q: Open source code with no license… can I fork it? [...]
> A: Short answer: absolutely not. [...]

https://github.com/blog/1530-choosing-an-open-source-license
http://choosealicense.com/
http://choosealicense.com/no-license/

**Comment by sahava** [comment]
Perfect, thanks for the feedback! I added the MIT Licence as per your recommendation.

**Comment by shazow** [comment]
Thank you!! :) :custard:
