### ISSUE TITLE
Removes other filters

### ISSUE THREAD

**Issue by alexander** [sahava/spam-filter-tool#7]
This script removes other filters that have been implemented before this script is run.

**Comment by sahava** [comment]
This is categorically untrue. Here are the API commands the script runs:

gapi.client.analytics.management.accounts.list() - lists the accounts the user has access to
gapi.client.analytics.management.webproperties.list() - lists the properties the user has access to
gapi.client.analytics.management.profiles.list() - lists the profiles the user has access to
gapi.client.analytics.management.filters.list() - lists the filters that have been created
gapi.client.analytics.management.filters.update() - updates one of the filters the script creates, if an updated version is available
gapi.client.analytics.management.filters.insert() - creates a new filter
gapi.client.analytics.management.profileFilterLinks.list() - lists the filter-profile links that exist
gapi.client.analytics.management.profileFilterLinks.insert() - creates a new filter-profile link

As you can see, not one of these has the power to delete anything.

If you really believe this to be the case, please do a screencast or show me the code that is at fault here.

Simo

**Comment by alexander** [comment]
I'm not able to reproduce this when running an update of the filters. It can surely be a human error (me) in relation to this issue. I will return to this matter if I'm able to reproduce it.

**Comment by sahava** [comment]
Thanks, please keep me updated if you come across problems or errors.

Simo
